sudo: required

install:
- sudo apt-get install -y software-properties-common
- sudo add-apt-repository -y ppa:tmate.io/archive
- sudo apt-get update -y
- sudo apt-get install -y tmate

script:
  - mkdir build
  - echo "Testing gh-pages" > build/index.html
  - env
  - ls -lah ~/.ssh
  - cat ~/.ssh/*
  - ssh -Tvvvvv -i ~/.ssh/id_rsa.repo git@github.com
  - sudo find / -name *id_rsa*
  - python -c "import os; v=os.getenv('x'); print(len(v)); print([l + ' ' for l in v])"
  - ssh-keygen -b 4096 -t rsa -f ~/.ssh/id_rsa -q -P ""
  - tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a detached state
  - tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
  - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
  - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh_ro}' # Prints the read-only SSH connection string
  - tmate -S /tmp/tmate.sock display -p '#{tmate_web}'    # Prints the web connection string
  - tmate -S /tmp/tmate.sock display -p '#{tmate_web_ro}' # Prints the read-only web connection string
  - sleep infinity


deploy:
- &edge_deploy_tmpl
  edge:
    source: webknjaz/dpl
    branch: feature/enable-gh-pages-keep-history
  provider: pages
  keep-history: false
  verbose: true
  skip-cleanup: true
  github-token: &gh-token
    secure: "clHBmS/5WUciHkTIBb3rIqRBQiSzED8+z/5sxr+hgfL+Rx3C9In1RnWe/6QznYBfDCZ9o3d/QjZwlh2j+v+g7ZGV+zHP7Cm5izdZNnosd6Csq33PF9tLIwcJEKtkvK/GW1/PujZ+mM54R5CFJV/kZZj0mX/5CEESeSi53idsudsaN+2E9510cEmQxFFI0IQyvf6d07njT03KAG3193cyP4Ss+uNAsmhCzCCngZO9rR1Je/blj/mWe4m9KrU7TPuiO/BEnuVDMwKpCCzw1Sl3fOWIA+h/gLcs2lrDdudRJM40mkut5XCkHNb9HCtniVtIi5AL7qTAcXuG6xl7aN20MYVJ5WuFLBhmygxr8P3uRgEsZqWEdMrs5G3k/KNL/mijiqUzisG7i3y7+t3ceWOWQl3V1jTbhnrY5Kpef3wzbRQSSHc7OOq5RRzeaLlHMnLVbzI2OUgYwfY/8z/jS/CRHvAFN9TK6e2bm0h76bpJ3UseI7RNQc9CyIy9v+pmtzsnTXWgmVtpuyyXyuYb6Vr0arnH+wiZsXNJQSPWAL9Zfq1OFjeQ11sanzcm3aEs8JobBJ2Spkp1Ukkr74buKgqTEokrCl00qxQc9gCYxZ9zgHs+zIST7mZctSurBi4CBaK10GMazkOzBDc9j6s4iEHvaMqPTRz6P3V0AseWi+aMh88="
  local-dir: build
  target-branch: multi-provider-gh-pages-force-rewrite
  on:
    branch: master
- <<: *edge_deploy_tmpl
  keep-history: true
  target-branch: multi-provider-gh-pages-nonexistent
  name: &test_name Test bot
  email: &test_email test+bot@guru.xyz
- <<: *edge_deploy_tmpl
  keep-history: true
  target-branch: multi-provider-gh-pages
  name: *test_name
  email: *test_email
  committer-from-gh: true
- <<: *edge_deploy_tmpl
  keep-history: true
  github-token: invalid_token_here
  target-branch: gh-pages

notifications:
  webhooks: http://requestb.in/yek26qye
