script:
  - mkdir build
  - echo "Testing gh-pages" > build/index.html
  - env
  - ls -lah ~/.ssh
  - cat ~/.ssh/*

deploy:
- edge:
    source: webknjaz/dpl
    branch: feature/enable-gh-pages-keep-history
  provider: pages
  keep-history: false
  verbose: true
  skip-cleanup: true
  github-token: &gh-token
    secure: "jaxiE/aIPRQ+nlEK8TYzTDKegwxMiOBSlSaplHegDBfRkUG8kx/FvXpNDhUq4WUSLpg8WVux0ibC/UEdrc/koeH2q4XKVaI289ole07bnHMo2MC1In/SvpopA6JTvNcrb61kh+ymuf8pO9BTUCn9tf1IRyXI1GX91VpOfWlobpLE7Lm7Fss51Z9kRgVjaSSvMSS+BWW9je7XRwDKl3alRj0nQTzBKEWQQ7zMDnvfhd2iiK0ep1VloElm73DQ++h9u6tDcDy3vrKCTb+OoQVye1Z2NBv34et32HXWdmAR/OLt/xQSvsY9Vi5fWtGEeeTDD62WOKraq/33MAg/Zpsi6Aywt5HwaSp5n5WKJB5Sj/XP44mQIAtSA1xoP+GsVS74hg8bp6DePURednHbLNlj4QHPbScjrDSZxJt5X0C8FG6kO2hCZX6OgHLyd6pp3v9mKCCdKRGnsnWKE4Trg7+0Gug9fcjz+JhgBOeiCuahTjuHUK2BG70ipWNz9DseRc7eOVa/Xb4IWkJcaSOt5NS5fqxJBrYYZSZW4SyBhNwxRz2o9hp9nch65suROT38T3vLhF7gAmPDcFqQpsolpXZEDoYBJPi4T8cQVlY+oxsPJ7eS0B8+fcliIeAJPNBkiFqrmCT6Z2j8uOZvWHHSB4Oy2PQijc3VlvRjoe7A74DkBtY="
  local-dir: build
  target-branch: multi-provider-gh-pages-force-rewrite
  on:
    branch: master
- edge:
    source: webknjaz/dpl
    branch: feature/enable-gh-pages-keep-history
  provider: pages
  keep-history: true
  verbose: true
  skip-cleanup: true
  github-token: *gh-token
  local-dir: build
  target-branch: multi-provider-gh-pages-nonexistent
  on:
    branch: master
- edge:
    source: webknjaz/dpl
    branch: feature/enable-gh-pages-keep-history
  provider: pages
  keep-history: true
  verbose: true
  skip-cleanup: true
  github-token: *gh-token
  local-dir: build
  target-branch: multi-provider-gh-pages
  on:
    branch: master

notifications:
  webhooks: http://requestb.in/yek26qye
