script:
  - mkdir build
  - echo "Testing gh-pages" > build/index.html

deploy:
  edge:
    source: webknjaz/dpl
    branch: master
  provider: pages
  github-token: xxx
  local-dir: build
  on:
    branch: master

notifications:
  webhooks: "http://requestb.in/zqdupszq"
